
export const FEDERAL_LAWS = [
  { id: '1', name: 'Administrative Procedure Act' },
  { id: '2', name: 'Admiralty Law' },
  { id: '3', name: 'Age Discrimination in Employment Act' },
  { id: '4', name: 'Americans with Disabilities Act' },
  { id: '5', name: 'Animal Welfare Act' },
  { id: '6', name: 'Antitrust Law (Sherman Act, Clayton Act)' },
  { id: '7', name: 'Bankruptcy Law (Title 11)' },
  { id: '8', name: 'Child Labor Laws (Fair Labor Standards Act)' },
  { id: '9', name: 'Civil Rights Act of 1964' },
  { id: '10', name: 'Clean Air Act' },
  { id: '11', name: 'Clean Water Act' },
  { id: '12', name: 'Comprehensive Environmental Response, Compensation, and Liability Act (Superfund)' },
  { id: '13', name: 'Consolidated Omnibus Budget Reconciliation Act (COBRA)' },
  { id: '14', name: 'Consumer Credit Protection Act' },
  { id: '15', name: 'Copyright Law (Title 17)' },
  { id: '16', name: 'Customs and Border Protection Regulations' },
  { id: '17', name: 'Dodd-Frank Wall Street Reform and Consumer Protection Act' },
  { id: '18', name: 'Drug Enforcement Administration (DEA) Regulations' },
  { id: '19', name: 'Employee Retirement Income Security Act (ERISA)' },
  { id: '20', name: 'Endangered Species Act' },
  { id: '21', name: 'Energy Policy Act' },
  { id: '22', name: 'Equal Credit Opportunity Act' },
  { id: '23', name: 'Equal Pay Act of 1963' },
  { id: '24', name: 'Fair Credit Reporting Act' },
  { id: '25', name: 'Fair Debt Collection Practices Act' },
  { id: '26', name: 'Fair Housing Act' },
  { id: '27', name: 'Fair Labor Standards Act (FLSA)' },
  { id: '28', name: 'Family and Medical Leave Act (FMLA)' },
  { id: '29', name: 'Federal Aviation Administration (FAA) Regulations' },
  { id's: '30', name: 'Federal Communications Commission (FCC) Regulations' },
  { id: '31', name: 'Federal Food, Drug, and Cosmetic Act' },
  { id: '32', name: 'Federal Information Security Management Act (FISMA)' },
  { id: '33', name: 'Federal Insecticide, Fungicide, and Rodenticide Act' },
  { id: '34', name: 'Federal Trade Commission (FTC) Act' },
  { id: '35', name: 'Freedom of Information Act (FOIA)' },
  { id: '36', name: 'Gramm-Leach-Bliley Act (Financial Services Modernization Act)' },
  { id: '37', name: 'Health Insurance Portability and Accountability Act (HIPAA)' },
  { id: '38', name: 'Immigration and Nationality Act' },
  { id: '39', name: 'Internal Revenue Code (Title 26)' },
  { id: '40', name: 'International Traffic in Arms Regulations (ITAR)' },
  { id: '41', name: 'Lanham Act (Trademarks)' },
  { id: '42', name: 'National Environmental Policy Act (NEPA)' },
  { id: '43', name: 'National Labor Relations Act (NLRA)' },
  { id: '44', name: 'Occupational Safety and Health Act (OSHA)' },
  { id: '45', name: 'Patent Law (Title 35)' },
  { id: '46', name: 'Patient Protection and Affordable Care Act (ACA)' },
  { id: '47', name: 'Racketeer Influenced and Corrupt Organizations (RICO) Act' },
  { id: '48', name: 'Resource Conservation and Recovery Act (RCRA)' },
  { id: '49', name: 'Sarbanes-Oxley Act (SOX)' },
  { id: '50', name: 'Securities Act of 1933' },
  { id: '51', name: 'Securities Exchange Act of 1934' },
  { id: '52', name: 'Social Security Act' },
  { id: '53', name: 'Telecommunications Act of 1996' },
  { id: '54', name: 'Uniform Commercial Code (UCC)' },
];
