
export const FEDERAL_LAWS = [
  { id: '1', name: 'Administrative Procedure Act', keywords: ['rulemaking', 'adjudication', 'agencies'] },
  { id: '2', name: 'Admiralty Law', keywords: ['maritime', 'shipping', 'ocean', 'jones act'] },
  { id: '3', name: 'Age Discrimination in Employment Act', keywords: ['ADEA', 'employment', 'age', 'discrimination'] },
  { id: '4', name: 'Americans with Disabilities Act', keywords: ['ADA', 'disability', 'wheelchair', 'accessibility', 'opdmd'] },
  { id: '5', name: 'Animal Welfare Act', keywords: ['animals', 'research', 'exhibition', 'usda'] },
  { id: '6', name: 'Antitrust Law (Sherman Act, Clayton Act)', keywords: ['competition', 'monopoly', 'collusion', 'ftc'] },
  { id: '7', name: 'Bankruptcy Law (Title 11)', keywords: ['debt', 'liquidation', 'chapter 7', 'chapter 13'] },
  { id: '8', name: 'Child Labor Laws (Fair Labor Standards Act)', keywords: ['flsa', 'minors', 'employment', 'work hours'] },
  { id: '9', name: 'Civil Rights Act of 1964', keywords: ['discrimination', 'segregation', 'employment', 'voting'] },
  { id: '10', name: 'Clean Air Act', keywords: ['air pollution', 'emissions', 'epa', 'smog'] },
  { id: '11', name: 'Clean Water Act', keywords: ['water pollution', 'wetlands', 'npdes', 'epa'] },
  { id: '12', name: 'Comprehensive Environmental Response, Compensation, and Liability Act (Superfund)', keywords: ['cercla', 'hazardous waste', 'cleanup', 'epa'] },
  { id: '13', name: 'Consolidated Omnibus Budget Reconciliation Act (COBRA)', keywords: ['health insurance', 'employment', 'continuation coverage'] },
  { id: '14', name: 'Consumer Credit Protection Act', keywords: ['tila', 'fcra', 'fdcpa', 'credit report'] },
  { id: '15', name: 'Copyright Law (Title 17)', keywords: ['copyright', 'intellectual property', 'fair use', 'dmca'] },
  { id: '16', name: 'Customs and Border Protection Regulations', keywords: ['cbp', 'import', 'export', 'tariffs', 'border'] },
  { id: '17', name: 'Dodd-Frank Wall Street Reform and Consumer Protection Act', keywords: ['financial reform', 'cfpb', 'volcker rule', 'derivatives'] },
  { id: '18', name: 'Drug Enforcement Administration (DEA) Regulations', keywords: ['dea', 'controlled substances', 'drug scheduling'] },
  { id: '19', name: 'Employee Retirement Income Security Act (ERISA)', keywords: ['pension', '401k', 'retirement plan', 'fiduciary'] },
  { id: '20', name: 'Endangered Species Act', keywords: ['esa', 'wildlife', 'conservation', 'threatened species'] },
  { id: '21', name: 'Energy Policy Act', keywords: ['energy', 'renewable fuel', 'oil and gas', 'efficiency'] },
  { id: '22', name: 'Equal Credit Opportunity Act', keywords: ['ecoa', 'credit', 'discrimination', 'lending'] },
  { id: '23', name: 'Equal Pay Act of 1963', keywords: ['epa', 'wages', 'gender discrimination', 'equal pay'] },
  { id: '24', name: 'Fair Credit Reporting Act', keywords: ['fcra', 'credit report', 'consumer rights', 'dispute'] },
  { id: '25', name: 'Fair Debt Collection Practices Act', keywords: ['fdcpa', 'debt collection', 'harassment'] },
  { id: '26', name: 'Fair Housing Act', keywords: ['fha', 'housing', 'discrimination', 'landlord'] },
  { id: '27', name: 'Fair Labor Standards Act (FLSA)', keywords: ['minimum wage', 'overtime', 'child labor'] },
  { id: '28', name: 'Family and Medical Leave Act (FMLA)', keywords: ['fmla', 'leave', 'medical leave', 'family leave'] },
  { id: '29', name: 'Federal Aviation Administration (FAA) Regulations', keywords: ['faa', 'aviation', 'aircraft', 'pilot license'] },
  { id: '30', name: 'Federal Communications Commission (FCC) Regulations', keywords: ['fcc', 'broadcast', 'telecommunications', 'net neutrality'] },
  { id: '31', name: 'Federal Food, Drug, and Cosmetic Act', keywords: ['fda', 'food safety', 'drug approval', 'medical devices'] },
  { id: '32', name: 'Federal Information Security Management Act (FISMA)', keywords: ['fisma', 'cybersecurity', 'information security', 'nist'] },
  { id: '33', name: 'Federal Insecticide, Fungicide, and Rodenticide Act', keywords: ['fifra', 'pesticides', 'epa', 'herbicides'] },
  { id: '34', name: 'Federal Trade Commission (FTC) Act', keywords: ['ftc', 'consumer protection', 'antitrust', 'false advertising'] },
  { id: '35', name: 'Freedom of Information Act (FOIA)', keywords: ['foia', 'public records', 'transparency', 'government'] },
  { id: '36', name: 'Gramm-Leach-Bliley Act (Financial Services Modernization Act)', keywords: ['glba', 'financial privacy', 'data security'] },
  { id: '37', name: 'Health Insurance Portability and Accountability Act (HIPAA)', keywords: ['hipaa', 'health privacy', 'medical records', 'phi'] },
  { id: '38', name: 'Immigration and Nationality Act', keywords: ['ina', 'immigration', 'visa', 'citizenship', 'asylum'] },
  { id: '39', name: 'Internal Revenue Code (Title 26)', keywords: ['irs', 'taxes', 'income tax', 'tax code'] },
  { id: '40', name: 'International Traffic in Arms Regulations (ITAR)', keywords: ['itar', 'defense export', 'usml', 'arms control'] },
  { id: '41', name: 'Lanham Act (Trademarks)', keywords: ['trademark', 'intellectual property', 'brand', 'infringement'] },
  { id: '42', name: 'National Environmental Policy Act (NEPA)', keywords: ['nepa', 'environmental impact', 'eis', 'ceq'] },
  { id: '43', name: 'National Labor Relations Act (NLRA)', keywords: ['nlra', 'unions', 'collective bargaining', 'nlrb'] },
  { id: '44', name: 'Occupational Safety and Health Act (OSHA)', keywords: ['osha', 'workplace safety', 'health standards'] },
  { id: '45', name: 'Patent Law (Title 35)', keywords: ['patent', 'invention', 'intellectual property', 'uspto'] },
  { id: '46', name: 'Patient Protection and Affordable Care Act (ACA)', keywords: ['aca', 'obamacare', 'health insurance', 'marketplace'] },
  { id: '47', name: 'Racketeer Influenced and Corrupt Organizations (RICO) Act', keywords: ['rico', 'organized crime', 'racketeering'] },
  { id: '48', name: 'Resource Conservation and Recovery Act (RCRA)', keywords: ['rcra', 'hazardous waste', 'recycling', 'epa'] },
  { id: '49', name: 'Sarbanes-Oxley Act (SOX)', keywords: ['sox', 'corporate governance', 'accounting', 'sec'] },
  { id: '50', name: 'Securities Act of 1933', keywords: ['securities', 'ipo', 'prospectus', 'sec'] },
  { id: '51', name: 'Securities Exchange Act of 1934', keywords: ['securities', 'sec', 'insider trading', '10-k'] },
  { id: '52', name: 'Social Security Act', keywords: ['social security', 'retirement', 'disability', 'ssa'] },
  { id: '53', name: 'Telecommunications Act of 1996', keywords: ['telecom', 'internet', 'fcc', 'section 230'] },
  { id: '54', name: 'Uniform Commercial Code (UCC)', keywords: ['ucc', 'commercial law', 'sales', 'secured transactions'] },
].sort((a, b) => a.name.localeCompare(b.name));
