
export const ALABAMA_CODE = [
    { id: '1', name: 'General Provisions' },
    { id: '2', name: 'Agriculture' },
    { id: '3', name: 'Animals' },
    { id: '4', name: 'Aviation' },
    { id: '5', name: 'Banks and Financial Institutions' },
    { id: '6', name: 'Civil Practice' },
    { id: '7', name: 'Commercial Code' },
    { id: '8', name: 'Commercial Law and Consumer Protection' },
    { id: '9', name: 'Conservation and Natural Resources' },
    { id: '10A', name: 'Business and Nonprofit Entities' },
    { id: '11', name: 'Counties and Municipal Corporations' },
    { id: '12', name: 'Courts' },
    { id: '13A', name: 'Criminal Code' },
    { id: '14', name: 'Criminal Correctional and Detention Facilities' },
    { id: '15', name: 'Criminal Procedure' },
    { id: '16', name: 'Education' },
    { id: '17', name: 'Elections' },
    { id: '18', name: 'Eminent Domain' },
    { id: '19', name: 'Fiduciaries and Trusts' },
    { id: '20', name: 'Food, Drugs and Cosmetics' },
    { id: '21', name: 'Handicapped Persons' },
    { id: '22', name: 'Health, Mental Health and Environmental Control' },
    { id: '23', name: 'Highways, Roads, Bridges and Ferries' },
    { id: '24', name: 'Housing' },
    { id: '25', name: 'Industrial Relations and Labor' },
    { id: '26', name: 'Infants and Incompetents' },
    { id: '27', name: 'Insurance' },
    { id: '28', name: 'Intoxicating Liquor, Malt Beverages and Wine' },
    { id: '29', name: 'Legislature' },
    { id: '30', name: 'Marital and Domestic Relations' },
    { id: '31', name: 'Military Affairs and Civil Defense' },
    { id: '32', name: 'Motor Vehicles and Traffic' },
    { id: '33', name: 'Navigation and Watercourses' },
    { id: '34', name: 'Professions and Occupations' },
    { id: '35', name: 'Property' },
    { id: '36', name: 'Public Officers and Employees' },
    { id: '37', name: 'Public Utilities and Public Transportation' },
    { id: '38', name: 'Public Welfare' },
    { id: '39', name: 'Public Works' },
    { id: '40', name: 'Revenue and Taxation' },
    { id: '41', name: 'State Government' },
    { id: '42', name: 'United States' },
    { id: '43', name: 'Wills and Decedents\' Estates' },
    { id: '44', name: '(Reserved)' },
    { id: '45', name: 'Local Laws' },
].sort((a, b) => a.name.localeCompare(b.name));
