
export const ARIZONA_REVISED_STATUTES = [
    { id: '1', name: 'General Provisions' },
    { id: '2', name: 'Aeronautics' },
    { id: '3', name: 'Agriculture' },
    { id: '4', name: 'Alcoholic Beverages' },
    { id: '5', name: 'Amusements and Sports' },
    { id: '6', name: 'Banks and Financial Institutions' },
    { id: '7', name: 'Blank' },
    { id: '8', name: 'Children' },
    { id: '9', name: 'Cities and Towns' },
    { id: '10', name: 'Corporations and Associations' },
    { id: '11', name: 'Counties' },
    { id: '12', name: 'Courts and Civil Proceedings' },
    { id: '13', name: 'Criminal Code' },
    { id: '14', name: 'Trusts, Estates and Protective Proceedings' },
    { id: '15', name: 'Education' },
    { id: '16', name: 'Elections and Electors' },
    { id: '17', name: 'Game and Fish' },
    { id: '18', name: 'Highways and Bridges' },
    { id: '19', name: 'Initiative, Referendum and Recall' },
    { id: '20', name: 'Insurance' },
    { id: '21', name: 'Juries' },
    { id: '22', name: 'Justices of the Peace and Other Courts Not of Record' },
    { id: '23', name: 'Labor' },
    { id: '24', name: 'Livestock and Animals' },
    { id: '25', name: 'Marital and Domestic Relations' },
    { id: '26', name: 'Military Affairs and Emergency Management' },
    { id: '27', name: 'Minerals, Oil and Gas' },
    { id: '28', name: 'Transportation' },
    { id: '29', name: 'Partnership' },
    { id: '30', name: 'Power' },
    { id: '31', name: 'Prisons and Prisoners' },
    { id: '32', name: 'Professions and Occupations' },
    { id: '33', name: 'Property' },
    { id: '34', name: 'Public Buildings and Improvements' },
    { id: '35', name: 'Public Finances' },
    { id: '36', name: 'Public Health and Safety' },
    { id: '37', name: 'Public Lands' },
    { id: '38', name: 'Public Officers and Employees' },
    { id: '39', name: 'Public Records, Printing and Notices' },
    { id: '40', name: 'Public Utilities and Carriers' },
    { id: '41', name: 'State Government' },
    { id: '42', name: 'Taxation' },
    { id: '43', name: 'Taxation of Income' },
    { id: '44', name: 'Trade and Commerce' },
    { id: '45', name: 'Waters' },
    { id: '46', name: 'Welfare' },
    { id: '47', name: 'Uniform Commercial Code' },
    { id: '48', name: 'Special Taxing Districts' },
    { id: '49', name: 'The Environment' },
];
