
export const ARIZONA_TRIBES = [
  'Ak-Chin Indian Community',
  'Cocopah Indian Tribe',
  'Colorado River Indian Tribes',
  'Fort McDowell Yavapai Nation',
  'Fort Mojave Indian Tribe',
  'Gila River Indian Community',
  'Havasupai Tribe',
  'Hopi Tribe',
  'Hualapai Tribe',
  'Kaibab Band of Paiute Indians',
  'Navajo Nation',
  'Pascua Yaqui Tribe',
  'Pueblo of Zuni',
  'Quechan Tribe',
  'Salt River Pima-Maricopa Indian Community',
  'San Carlos Apache Tribe',
  'San Juan Southern Paiute Tribe',
  'Tohono O\'odham Nation',
  'Tonto Apache Tribe',
  'White Mountain Apache Tribe',
  'Yavapai-Apache Nation',
  'Yavapai-Prescott Indian Tribe',
].sort((a, b) => a.localeCompare(b));
