
'use client';

import React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, Home, Accessibility } from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';

const fileTree = [
  { "number": 1, "name": "C:", "type": "folder", "indent": 0 },
  { "number": 2, "name": "projects", "type": "folder", "indent": 1 },
  { "number": 3, "name": "The-Law-Says.Com", "type": "folder", "indent": 2 },
  { "number": 4, "name": ".env", "type": "file", "indent": 3 },
  { "number": 5, "name": "README.md", "type": "file", "indent": 3 },
  { "number": 6, "name": "apphosting.yaml", "type": "file", "indent": 3 },
  { "number": 7, "name": "components.json", "type": "file", "indent": 3 },
  { "number": 8, "name": "firebase.json", "type": "file", "indent": 3 },
  { "number": 9, "name": "next.config.ts", "type": "file", "indent": 3 },
  { "number": 10, "name": "package.json", "type": "file", "indent": 3 },
  { "number": 11, "name": "tailwind.config.ts", "type": "file", "indent": 3 },
  { "number": 12, "name": "tsconfig.json", "type": "file", "indent": 3 },
  { "number": 13, "name": "src", "type": "folder", "indent": 3 },
  { "number": 14, "name": "ai", "type": "folder", "indent": 4 },
  { "number": 15, "name": "dev.ts", "type": "file", "indent": 5 },
  { "number": 16, "name": "genkit.ts", "type": "file", "indent": 5 },
  { "number": 17, "name": "flows", "type": "folder", "indent": 5 },
  { "number": 18, "name": "get-legal-guidance.ts", "type": "file", "indent": 6 },
  { "number": 19, "name": "translate-text.ts", "type": "file", "indent": 6 },
  { "number": 20, "name": "app", "type": "folder", "indent": 4 },
  { "number": 21, "name": "actions.ts", "type": "file", "indent": 5 },
  { "number": 22, "name": "globals.css", "type": "file", "indent": 5 },
  { "number": 23, "name": "layout.tsx", "type": "file", "indent": 5 },
  { "number": 24, "name": "page.tsx", "type": "file", "indent": 5 },
  { "number": 25, "name": "translate", "type": "folder", "indent": 5 },
  { "number": 26, "name": "page.tsx", "type": "file", "indent": 6 },
  { "number": 27, "name": "the-code", "type": "folder", "indent": 5 },
  { "number": 28, "name": "page.tsx", "type": "file", "indent": 6 },
  { "number": 29, "name": "federal-laws", "type": "folder", "indent": 5 },
  { "number": 30, "name": "page.tsx", "type": "file", "indent": 6 },
  { "number": 31, "name": "[id]", "type": "folder", "indent": 6 },
  { "number": 32, "name": "client-page.tsx", "type": "file", "indent": 7 },
  { "number": 33, "name": "page.tsx", "type": "file", "indent": 7 },
  { "number": 34, "name": "guidance", "type": "folder", "indent": 5 },
  { "number": 35, "name": "page.tsx", "type": "file", "indent": 6 },
  { "number": 36, "name": "ask", "type": "folder", "indent": 6 },
  { "number": 37, "name": "page.tsx", "type": "file", "indent": 7 },
  { "number": 38, "name": "alabama", "type": "folder", "indent": 6 },
  { "number": 39, "name": "page.tsx", "type": "file", "indent": 7 },
  { "number": 40, "name": "state-laws", "type": "folder", "indent": 7 },
  { "number": 41, "name": "page.tsx", "type": "file", "indent": 8 },
  { "number": 42, "name": "[id]", "type": "folder", "indent": 8 },
  { "number": 43, "name": "client-page.tsx", "type": "file", "indent": 9 },
  { "number": 44, "name": "page.tsx", "type": "file", "indent": 9 },
  { "number": 45, "name": "arizona", "type": "folder", "indent": 6 },
  { "number": 46, "name": "page.tsx", "type": "file", "indent": 7 },
  { "number": 47, "name": "county-laws", "type": "folder", "indent": 7 },
  { "number": 48, "name": "page.tsx", "type": "file", "indent": 8 },
  { "number": 49, "name": "[county]", "type": "folder", "indent": 8 },
  { "number": 50, "name": "page.tsx", "type": "file", "indent": 9 },
  { "number": 51, "name": "apache", "type": "folder", "indent": 8 },
  { "number": 52, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 53, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 54, "name": "cochise", "type": "folder", "indent": 8 },
  { "number": 55, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 56, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 57, "name": "coconino", "type": "folder", "indent": 8 },
  { "number": 58, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 59, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 60, "name": "gila", "type": "folder", "indent": 8 },
  { "number": 61, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 62, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 63, "name": "graham", "type": "folder", "indent": 8 },
  { "number": 64, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 65, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 66, "name": "greenlee", "type": "folder", "indent": 8 },
  { "number": 67, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 68, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 69, "name": "la-paz", "type": "folder", "indent": 8 },
  { "number": 70, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 71, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 72, "name": "maricopa", "type": "folder", "indent": 8 },
  { "number": 73, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 74, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 75, "name": "mohave", "type": "folder", "indent": 8 },
  { "number": 76, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 77, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 78, "name": "navajo", "type": "folder", "indent": 8 },
  { "number": 79, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 80, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 81, "name": "pima", "type": "folder", "indent": 8 },
  { "number": 82, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 83, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 84, "name": "pinal", "type": "folder", "indent": 8 },
  { "number": 85, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 86, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 87, "name": "santa-cruz", "type": "folder", "indent": 8 },
  { "number": 88, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 89, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 90, "name": "yavapai", "type": "folder", "indent": 8 },
  { "number": 91, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 92, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 93, "name": "yuma", "type": "folder", "indent": 8 },
  { "number": 94, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 95, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 96, "name": "municipality-laws", "type": "folder", "indent": 7 },
  { "number": 97, "name": "page.tsx", "type": "file", "indent": 8 },
  { "number": 98, "name": "[municipality]", "type": "folder", "indent": 8 },
  { "number": 99, "name": "page.tsx", "type": "file", "indent": 9 },
  { "number": 100, "name": "[id]", "type": "folder", "indent": 9 },
  { "number": 101, "name": "page.tsx", "type": "file", "indent": 10 },
  { "number": 102, "name": "client-page.tsx", "type": "file", "indent": 10 },
  { "number": 103, "name": "[section]", "type": "folder", "indent": 10 },
  { "number": 104, "name": "page.tsx", "type": "file", "indent": 11 },
  { "number": 105, "name": "[subsection]", "type": "folder", "indent": 11 },
  { "number": 106, "name": "page.tsx", "type": "file", "indent": 12 },
  { "number": 107, "name": "state-laws", "type": "folder", "indent": 7 },
  { "number": 108, "name": "page.tsx", "type": "file", "indent": 8 },
  { "number": 109, "name": "[id]", "type": "folder", "indent": 8 },
  { "number": 110, "name": "page.tsx", "type": "file", "indent": 9 },
  { "number": 111, "name": "client-page.tsx", "type": "file", "indent": 9 },
  { "number": 112, "name": "tribal-laws", "type": "folder", "indent": 7 },
  { "number": 113, "name": "page.tsx", "type": "file", "indent": 8 },
  { "number": 114, "name": "[tribe]", "type": "folder", "indent": 8 },
  { "number": 115, "name": "page.tsx", "type": "file", "indent": 9 },
  { "number": 116, "name": "[state]", "type": "folder", "indent": 6 },
  { "number": 117, "name": "page.tsx", "type": "file", "indent": 7 },
  { "number": 118, "name": "components", "type": "folder", "indent": 4 },
  { "number": 119, "name": "logo.tsx", "type": "file", "indent": 5 },
  { "number": 120, "name": "ui", "type": "folder", "indent": 5 },
  { "number": 121, "name": "accordion.tsx", "type": "file", "indent": 6 },
  { "number": 122, "name": "alert-dialog.tsx", "type": "file", "indent": 6 },
  { "number": 123, "name": "alert.tsx", "type": "file", "indent": 6 },
  { "number": 124, "name": "avatar.tsx", "type": "file", "indent": 6 },
  { "number": 125, "name": "badge.tsx", "type": "file", "indent": 6 },
  { "number": 126, "name": "button.tsx", "type": "file", "indent": 6 },
  { "number": 127, "name": "calendar.tsx", "type": "file", "indent": 6 },
  { "number": 128, "name": "card.tsx", "type": "file", "indent": 6 },
  { "number": 129, "name": "carousel.tsx", "type": "file", "indent": 6 },
  { "number": 130, "name": "chart.tsx", "type": "file", "indent": 6 },
  { "number": 131, "name": "checkbox.tsx", "type": "file", "indent": 6 },
  { "number": 132, "name": "collapsible.tsx", "type": "file", "indent": 6 },
  { "number": 133, "name": "dialog.tsx", "type": "file", "indent": 6 },
  { "number": 134, "name": "dropdown-menu.tsx", "type": "file", "indent": 6 },
  { "number": 135, "name": "form.tsx", "type": "file", "indent": 6 },
  { "number": 136, "name": "input.tsx", "type": "file", "indent": 6 },
  { "number": 137, "name": "label.tsx", "type": "file", "indent": 6 },
  { "number": 138, "name": "menubar.tsx", "type": "file", "indent": 6 },
  { "number": 139, "name": "popover.tsx", "type": "file", "indent": 6 },
  { "number": 140, "name": "progress.tsx", "type": "file", "indent": 6 },
  { "number": 141, "name": "radio-group.tsx", "type": "file", "indent": 6 },
  { "number": 142, "name": "scroll-area.tsx", "type": "file", "indent": 6 },
  { "number": 143, "name": "select.tsx", "type": "file", "indent": 6 },
  { "number": 144, "name": "separator.tsx", "type": "file", "indent": 6 },
  { "number": 145, "name": "sheet.tsx", "type": "file", "indent": 6 },
  { "number": 146, "name": "sidebar.tsx", "type": "file", "indent": 6 },
  { "number": 147, "name": "skeleton.tsx", "type": "file", "indent": 6 },
  { "number": 148, "name": "slider.tsx", "type": "file", "indent": 6 },
  { "number": 149, "name": "switch.tsx", "type": "file", "indent": 6 },
  { "number": 150, "name": "table.tsx", "type": "file", "indent": 6 },
  { "number": 151, "name": "tabs.tsx", "type": "file", "indent": 6 },
  { "number": 152, "name": "textarea.tsx", "type": "file", "indent": 6 },
  { "number": 153, "name": "toast.tsx", "type": "file", "indent": 6 },
  { "number": 154, "name": "toaster.tsx", "type": "file", "indent": 6 },
  { "number": 155, "name": "tooltip.tsx", "type": "file", "indent": 6 },
  { "number": 156, "name": "context", "type": "folder", "indent": 4 },
  { "number": 157, "name": "language-context.tsx", "type": "file", "indent": 5 },
  { "number": 158, "name": "firebase", "type": "folder", "indent": 4 },
  { "number": 159, "name": "config.ts", "type": "file", "indent": 5 },
  { "number": 160, "name": "hooks", "type": "folder", "indent": 4 },
  { "number": 161, "name": "use-mobile.tsx", "type": "file", "indent": 5 },
  { "number": 162, "name": "use-toast.ts", "type": "file", "indent": 5 },
  { "number": 163, "name": "useTextToSpeech.ts", "type": "file", "indent": 5 },
  { "number": 164, "name": "lib", "type": "folder", "indent": 4 },
  { "number": 165, "name": "alabama-code.ts", "type": "file", "indent": 5 },
  { "number": 166, "name": "alabama-code-content.ts", "type": "file", "indent": 5 },
  { "number": 167, "name": "apache-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 168, "name": "apache-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 169, "name": "apache-junction-code.ts", "type": "file", "indent": 5 },
  { "number": 170, "name": "apache-junction-code-content.ts", "type": "file", "indent": 5 },
  { "number": 171, "name": "arizona-counties.ts", "type": "file", "indent": 5 },
  { "number": 172, "name": "arizona-municipalities.ts", "type": "file", "indent": 5 },
  { "number": 173, "name": "arizona-revised-statutes.ts", "type": "file", "indent": 5 },
  { "number": 174, "name": "arizona-revised-statutes-content.ts", "type": "file", "indent": 5 },
  { "number": 175, "name": "arizona-tribes.ts", "type": "file", "indent": 5 },
  { "number": 176, "name": "avondale-code.ts", "type": "file", "indent": 5 },
  { "number": 177, "name": "avondale-code-content.ts", "type": "file", "indent": 5 },
  { "number": 178, "name": "ak-chin-content.ts", "type": "file", "indent": 5 },
  { "number": 179, "name": "benson-code.ts", "type": "file", "indent": 5 },
  { "number": 180, "name": "benson-code-content.ts", "type": "file", "indent": 5 },
  { "number": 181, "name": "bisbee-code.ts", "type": "file", "indent": 5 },
  { "number": 182, "name": "bisbee-code-content.ts", "type": "file", "indent": 5 },
  { "number": 183, "name": "buckeye-code.ts", "type": "file", "indent": 5 },
  { "number": 184, "name": "buckeye-code-content.ts", "type": "file", "indent": 5 },
  { "number": 185, "name": "bullhead-city-code.ts", "type": "file", "indent": 5 },
  { "number": 186, "name": "bullhead-city-code-content.ts", "type": "file", "indent": 5 },
  { "number": 187, "name": "camp-verde-code.ts", "type": "file", "indent": 5 },
  { "number": 188, "name": "camp-verde-code-content.ts", "type": "file", "indent": 5 },
  { "number": 189, "name": "carefree-code.ts", "type": "file", "indent": 5 },
  { "number": 190, "name": "carefree-code-content.ts", "type": "file", "indent": 5 },
  { "number": 191, "name": "cave-creek-code.ts", "type": "file", "indent": 5 },
  { "number": 192, "name": "cave-creek-code-content.ts", "type": "file", "indent": 5 },
  { "number": 193, "name": "chandler-code.ts", "type": "file", "indent": 5 },
  { "number": 194, "name": "chandler-code-content.ts", "type": "file", "indent": 5 },
  { "number": 195, "name": "chino-valley-code.ts", "type": "file", "indent": 5 },
  { "number": 196, "name": "chino-valley-code-content.ts", "type": "file", "indent": 5 },
  { "number": 197, "name": "clarkdale-code.ts", "type": "file", "indent": 5 },
  { "number": 198, "name": "clarkdale-code-content.ts", "type": "file", "indent": 5 },
  { "number": 199, "name": "clifton-code.ts", "type": "file", "indent": 5 },
  { "number": 200, "name": "clifton-code-content.ts", "type": "file", "indent": 5 },
  { "number": 201, "name": "cochise-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 202, "name": "cochise-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 203, "name": "coconino-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 204, "name": "coconino-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 205, "name": "cocopah-content.ts", "type": "file", "indent": 5 },
  { "number": 206, "name": "colorado-river-indian-tribes-content.ts", "type": "file", "indent": 5 },
  { "number": 207, "name": "constants.ts", "type": "file", "indent": 5 },
  { "number": 208, "name": "coolidge-code.ts", "type": "file", "indent": 5 },
  { "number": 209, "name": "coolidge-code-content.ts", "type": "file", "indent": 5 },
  { "number": 210, "name": "cottonwood-code.ts", "type": "file", "indent": 5 },
  { "number": 211, "name": "cottonwood-code-content.ts", "type": "file", "indent": 5 },
  { "number": 212, "name": "dewey-humboldt-code.ts", "type": "file", "indent": 5 },
  { "number": 213, "name": "dewey-humboldt-code-content.ts", "type": "file", "indent": 5 },
  { "number": 214, "name": "douglas-code.ts", "type": "file", "indent": 5 },
  { "number": 215, "name": "douglas-code-content.ts", "type": "file", "indent": 5 },
  { "number": 216, "name": "duncan-code.ts", "type": "file", "indent": 5 },
  { "number": 217, "name": "duncan-code-content.ts", "type": "file", "indent": 5 },
  { "number": 218, "name": "eagar-code.ts", "type": "file", "indent": 5 },
  { "number": 219, "name": "eagar-code-content.ts", "type": "file", "indent": 5 },
  { "number": 220, "name": "el-mirage-code.ts", "type": "file", "indent": 5 },
  { "number": 221, "name": "el-mirage-code-content.ts", "type": "file", "indent": 5 },
  { "number": 222, "name": "eloy-code.ts", "type": "file", "indent": 5 },
  { "number": 223, "name": "eloy-code-content.ts", "type": "file", "indent": 5 },
  { "number": 224, "name": "federal-laws.ts", "type": "file", "indent": 5 },
  { "number": 225, "name": "federal-laws-content.ts", "type": "file", "indent": 5 },
  { "number": 226, "name": "flagstaff-code.ts", "type": "file", "indent": 5 },
  { "number": 227, "name": "flagstaff-code-content.ts", "type": "file", "indent": 5 },
  { "number": 228, "name": "florence-code.ts", "type": "file", "indent": 5 },
  { "number": 229, "name": "florence-code-content.ts", "type": "file", "indent": 5 },
  { "number": 230, "name": "fort-mcdowell-yavapai-nation-content.ts", "type": "file", "indent": 5 },
  { "number": 231, "name": "fort-mojave-indian-tribe-content.ts", "type": "file", "indent": 5 },
  { "number": 232, "name": "fountain-hills-code.ts", "type": "file", "indent": 5 },
  { "number": 233, "name": "fountain-hills-code-content.ts", "type": "file", "indent": 5 },
  { "number": 234, "name": "fredonia-code.ts", "type": "file", "indent": 5 },
  { "number": 235, "name": "fredonia-code-content.ts", "type": "file", "indent": 5 },
  { "number": 236, "name": "gila-bend-code.ts", "type": "file", "indent": 5 },
  { "number": 237, "name": "gila-bend-code-content.ts", "type": "file", "indent": 5 },
  { "number": 238, "name": "gila-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 239, "name": "gila-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 240, "name": "gila-river-indian-community-content.ts", "type": "file", "indent": 5 },
  { "number": 241, "name": "gilbert-code.ts", "type": "file", "indent": 5 },
  { "number": 242, "name": "gilbert-code-content.ts", "type": "file", "indent": 5 },
  { "number": 243, "name": "glendale-code.ts", "type": "file", "indent": 5 },
  { "number": 244, "name": "glendale-code-content.ts", "type": "file", "indent": 5 },
  { "number": 245, "name": "globe-code.ts", "type": "file", "indent": 5 },
  { "number": 246, "name": "globe-code-content.ts", "type": "file", "indent": 5 },
  { "number": 247, "name": "goodyear-code.ts", "type": "file", "indent": 5 },
  { "number": 248, "name": "goodyear-code-content.ts", "type": "file", "indent": 5 },
  { "number": 249, "name": "graham-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 250, "name": "graham-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 251, "name": "greenlee-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 252, "name": "greenlee-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 253, "name": "guadalupe-code.ts", "type": "file", "indent": 5 },
  { "number": 254, "name": "guadalupe-code-content.ts", "type": "file", "indent": 5 },
  { "number": 255, "name": "havasupai-content.ts", "type": "file", "indent": 5 },
  { "number": 256, "name": "hayden-code.ts", "type": "file", "indent": 5 },
  { "number": 257, "name": "hayden-code-content.ts", "type": "file", "indent": 5 },
  { "number": 258, "name": "holbrook-code.ts", "type": "file", "indent": 5 },
  { "number": 259, "name": "holbrook-code-content.ts", "type": "file", "indent": 5 },
  { "number": 260, "name": "hopi-content.ts", "type": "file", "indent": 5 },
  { "number": 261, "name": "hualapai-content.ts", "type": "file", "indent": 5 },
  { "number": 262, "name": "huachuca-city-code.ts", "type": "file", "indent": 5 },
  { "number": 263, "name": "huachuca-city-code-content.ts", "type": "file", "indent": 5 },
  { "number": 264, "name": "jerome-code.ts", "type": "file", "indent": 5 },
  { "number": 265, "name": "jerome-code-content.ts", "type": "file", "indent": 5 },
  { "number": 266, "name": "kaibab-paiute-content.ts", "type": "file", "indent": 5 },
  { "number": 267, "name": "kearny-code.ts", "type": "file", "indent": 5 },
  { "number": 268, "name": "kearny-code-content.ts", "type": "file", "indent": 5 },
  { "number": 269, "name": "kingman-code.ts", "type": "file", "indent": 5 },
  { "number": 270, "name": "kingman-code-content.ts", "type": "file", "indent": 5 },
  { "number": 271, "name": "la-paz-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 272, "name": "la-paz-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 273, "name": "lake-havasu-city-code.ts", "type": "file", "indent": 5 },
  { "number": 274, "name": "lake-havasu-city-code-content.ts", "type": "file", "indent": 5 },
  { "number": 275, "name": "languages.ts", "type": "file", "indent": 5 },
  { "number": 276, "name": "litchfield-park-code.ts", "type": "file", "indent": 5 },
  { "number": 277, "name": "litchfield-park-code-content.ts", "type": "file", "indent": 5 },
  { "number": 278, "name": "mammoth-code.ts", "type": "file", "indent": 5 },
  { "number": 279, "name": "mammoth-code-content.ts", "type": "file", "indent": 5 },
  { "number": 280, "name": "marana-code.ts", "type": "file", "indent": 5 },
  { "number": 281, "name": "marana-code-content.ts", "type": "file", "indent": 5 },
  { "number": 282, "name": "maricopa-code.ts", "type": "file", "indent": 5 },
  { "number": 283, "name": "maricopa-code-content.ts", "type": "file", "indent": 5 },
  { "number": 284, "name": "maricopa-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 285, "name": "maricopa-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 286, "name": "mesa-code.ts", "type": "file", "indent": 5 },
  { "number": 287, "name": "mesa-code-content.ts", "type": "file", "indent": 5 },
  { "number": 288, "name": "miami-code.ts", "type": "file", "indent": 5 },
  { "number": 289, "name": "miami-code-content.ts", "type": "file", "indent": 5 },
  { "number": 290, "name": "mohave-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 291, "name": "mohave-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 292, "name": "municipality-code-list.ts", "type": "file", "indent": 5 },
  { "number": 293, "name": "municipality-laws.ts", "type": "file", "indent": 5 },
  { "number": 294, "name": "navajo-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 295, "name": "navajo-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 296, "name": "navajo-nation-content.ts", "type": "file", "indent": 5 },
  { "number": 297, "name": "nogales-code.ts", "type": "file", "indent": 5 },
  { "number": 298, "name": "nogales-code-content.ts", "type": "file", "indent": 5 },
  { "number": 299, "name": "oro-valley-code.ts", "type": "file", "indent": 5 },
  { "number": 300, "name": "oro-valley-code-content.ts", "type": "file", "indent": 5 },
  { "number": 301, "name": "paradise-valley-code.ts", "type": "file", "indent": 5 },
  { "number": 302, "name": "paradise-valley-code-content.ts", "type": "file", "indent": 5 },
  { "number": 303, "name": "parker-code.ts", "type": "file", "indent": 5 },
  { "number": 304, "name": "parker-code-content.ts", "type": "file", "indent": 5 },
  { "number": 305, "name": "pascua-yaqui-content.ts", "type": "file", "indent": 5 },
  { "number": 306, "name": "patagonia-code.ts", "type": "file", "indent": 5 },
  { "number": 307, "name": "patagonia-code-content.ts", "type": "file", "indent": 5 },
  { "number": 308, "name": "payson-code.ts", "type": "file", "indent": 5 },
  { "number": 309, "name": "payson-code-content.ts", "type": "file", "indent": 5 },
  { "number": 310, "name": "peoria-code.ts", "type": "file", "indent": 5 },
  { "number": 311, "name": "peoria-code-content.ts", "type": "file", "indent": 5 },
  { "number": 312, "name": "phoenix-code.ts", "type": "file", "indent": 5 },
  { "number": 313, "name": "phoenix-code-content.ts", "type": "file", "indent": 5 },
  { "number": 314, "name": "pima-code.ts", "type": "file", "indent": 5 },
  { "number": 315, "name": "pima-code-content.ts", "type": "file", "indent": 5 },
  { "number": 316, "name": "pima-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 317, "name": "pima-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 318, "name": "pinal-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 319, "name": "pinal-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 320, "name": "pinetop-lakeside-code.ts", "type": "file", "indent": 5 },
  { "number": 321, "name": "pinetop-lakeside-code-content.ts", "type": "file", "indent": 5 },
  { "number": 322, "name": "prescott-code.ts", "type": "file", "indent": 5 },
  { "number": 323, "name": "prescott-code-content.ts", "type": "file", "indent": 5 },
  { "number": 324, "name": "prescott-valley-code.ts", "type": "file", "indent": 5 },
  { "number": 325, "name": "prescott-valley-code-content.ts", "type": "file", "indent": 5 },
  { "number": 326, "name": "prescott-valley-chapter-93-sections.ts", "type": "file", "indent": 5 },
  { "number": 327, "name": "prescott-valley-chapter-154-sections.ts", "type": "file", "indent": 5 },
  { "number": 328, "name": "prescott-valley-title-9-chapters.ts", "type": "file", "indent": 5 },
  { "number": 329, "name": "prescott-valley-title-15-chapters.ts", "type": "file", "indent": 5 },
  { "number": 330, "name": "pueblo-of-zuni-content.ts", "type": "file", "indent": 5 },
  { "number": 331, "name": "quartzsite-code.ts", "type": "file", "indent": 5 },
  { "number": 332, "name": "quartzsite-code-content.ts", "type": "file", "indent": 5 },
  { "number": 333, "name": "quechan-content.ts", "type": "file", "indent": 5 },
  { "number": 334, "name": "queen-creek-code.ts", "type": "file", "indent": 5 },
  { "number": 335, "name": "queen-creek-code-content.ts", "type": "file", "indent": 5 },
  { "number": 336, "name": "safford-code.ts", "type": "file", "indent": 5 },
  { "number": 337, "name": "safford-code-content.ts", "type": "file", "indent": 5 },
  { "number": 338, "name": "sahuarita-code.ts", "type": "file", "indent": 5 },
  { "number": 339, "name": "sahuarita-code-content.ts", "type": "file", "indent": 5 },
  { "number": 340, "name": "salt-river-pima-maricopa-content.ts", "type": "file", "indent": 5 },
  { "number": 341, "name": "san-carlos-apache-content.ts", "type": "file", "indent": 5 },
  { "number": 342, "name": "san-juan-southern-paiute-content.ts", "type": "file", "indent": 5 },
  { "number": 343, "name": "san-luis-code.ts", "type": "file", "indent": 5 },
  { "number": 344, "name": "san-luis-code-content.ts", "type": "file", "indent": 5 },
  { "number": 345, "name": "santa-cruz-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 346, "name": "santa-cruz-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 347, "name": "scottsdale-code.ts", "type": "file", "indent": 5 },
  { "number": 348, "name": "scottsdale-code-content.ts", "type": "file", "indent": 5 },
  { "number": 349, "name": "sedona-code.ts", "type": "file", "indent": 5 },
  { "number": 350, "name": "sedona-code-content.ts", "type": "file", "indent": 5 },
  { "number": 351, "name": "show-low-code.ts", "type": "file", "indent": 5 },
  { "number": 352, "name": "show-low-code-content.ts", "type": "file", "indent": 5 },
  { "number": 353, "name": "sierra-vista-code.ts", "type": "file", "indent": 5 },
  { "number": 354, "name": "sierra-vista-code-content.ts", "type": "file", "indent": 5 },
  { "number": 355, "name": "snowflake-code.ts", "type": "file", "indent": 5 },
  { "number": 356, "name": "snowflake-code-content.ts", "type": "file", "indent": 5 },
  { "number": 357, "name": "somerton-code.ts", "type": "file", "indent": 5 },
  { "number": 358, "name": "somerton-code-content.ts", "type": "file", "indent": 5 },
  { "number": 359, "name": "south-tucson-code.ts", "type": "file", "indent": 5 },
  { "number": 360, "name": "south-tucson-code-content.ts", "type": "file", "indent": 5 },
  { "number": 361, "name": "springerville-code.ts", "type": "file", "indent": 5 },
  { "number": 362, "name": "springerville-code-content.ts", "type": "file", "indent": 5 },
  { "number": 363, "name": "st-johns-code.ts", "type": "file", "indent": 5 },
  { "number": 364, "name": "st-johns-code-content.ts", "type": "file", "indent": 5 },
  { "number": 365, "name": "star-valley-code.ts", "type": "file", "indent": 5 },
  { "number": 366, "name": "star-valley-code-content.ts", "type": "file", "indent": 5 },
  { "number": 367, "name": "superior-code.ts", "type": "file", "indent": 5 },
  { "number": 368, "name": "superior-code-content.ts", "type": "file", "indent": 5 },
  { "number": 369, "name": "surprise-code.ts", "type": "file", "indent": 5 },
  { "number": 370, "name": "surprise-code-content.ts", "type": "file", "indent": 5 },
  { "number": 371, "name": "taylor-code.ts", "type": "file", "indent": 5 },
  { "number": 372, "name": "taylor-code-content.ts", "type": "file", "indent": 5 },
  { "number": 373, "name": "tempe-code.ts", "type": "file", "indent": 5 },
  { "number": 374, "name": "tempe-code-content.ts", "type": "file", "indent": 5 },
  { "number": 375, "name": "thatcher-code.ts", "type": "file", "indent": 5 },
  { "number": 376, "name": "thatcher-code-content.ts", "type": "file", "indent": 5 },
  { "number": 377, "name": "tohono-oodham-content.ts", "type": "file", "indent": 5 },
  { "number": 378, "name": "tolleson-code.ts", "type": "file", "indent": 5 },
  { "number": 379, "name": "tolleson-code-content.ts", "type": "file", "indent": 5 },
  { "number": 380, "name": "tombstone-code.ts", "type": "file", "indent": 5 },
  { "number": 381, "name": "tombstone-code-content.ts", "type": "file", "indent": 5 },
  { "number": 382, "name": "tonto-apache-content.ts", "type": "file", "indent": 5 },
  { "number": 383, "name": "tucson-code.ts", "type": "file", "indent": 5 },
  { "number": 384, "name": "tucson-code-content.ts", "type": "file", "indent": 5 },
  { "number": 385, "name": "utils.ts", "type": "file", "indent": 5 },
  { "number": 386, "name": "wellton-code.ts", "type": "file", "indent": 5 },
  { "number": 387, "name": "wellton-code-content.ts", "type": "file", "indent": 5 },
  { "number": 388, "name": "white-mountain-apache-content.ts", "type": "file", "indent": 5 },
  { "number": 389, "name": "wickenburg-code.ts", "type": "file", "indent": 5 },
  { "number": 390, "name": "wickenburg-code-content.ts", "type": "file", "indent": 5 },
  { "number": 391, "name": "willcox-code.ts", "type": "file", "indent": 5 },
  { "number": 392, "name": "willcox-code-content.ts", "type": "file", "indent": 5 },
  { "number": 393, "name": "williams-code.ts", "type": "file", "indent": 5 },
  { "number": 394, "name": "williams-code-content.ts", "type": "file", "indent": 5 },
  { "number": 395, "name": "winkelman-code.ts", "type": "file", "indent": 5 },
  { "number": 396, "name": "winkelman-code-content.ts", "type": "file", "indent": 5 },
  { "number": 397, "name": "winslow-code.ts", "type": "file", "indent": 5 },
  { "number": 398, "name": "winslow-code-content.ts", "type": "file", "indent": 5 },
  { "number": 399, "name": "yavapai-apache-content.ts", "type": "file", "indent": 5 },
  { "number": 400, "name": "yavapai-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 401, "name": "yavapai-county-ordinances-content.ts", "type": "file", "indent": 5 },
  { "number": 402, "name": "yavapai-prescott-content.ts", "type": "file", "indent": 5 },
  { "number": 403, "name": "youngtown-code.ts", "type": "file", "indent": 5 },
  { "number": 404, "name": "youngtown-code-content.ts", "type": "file", "indent": 5 },
  { "number": 405, "name": "yuma-code.ts", "type": "file", "indent": 5 },
  { "number": 406, "name": "yuma-code-content.ts", "type": "file", "indent": 5 },
  { "number": 407, "name": "yuma-county-ordinances.ts", "type": "file", "indent": 5 },
  { "number": 408, "name": "yuma-county-ordinances-content.ts", "type": "file", "indent": 5 },
];

export default function TheCodePage() {
  const router = useRouter();

  return (
    <div className="flex h-screen flex-col items-center justify-center bg-black p-4">
      <div className="flex h-[90svh] w-full max-w-2xl flex-col bg-background shadow-2xl">
        <header className="flex-shrink-0 rounded-t-2xl border-x-2 border-t-2 border-b-2 border-destructive bg-muted p-2 text-center text-3xl font-bold text-destructive-foreground shadow-md">
          <Link href="/the-code">The Code</Link>
        </header>

        <ScrollArea className="flex-grow border-x-2 border-destructive">
          <div className="p-2 text-center text-sm font-bold text-destructive-foreground">
              <Link href="/" className="flex items-center justify-center gap-2">
                  <Home className="h-4 w-4" />
                  Home
              </Link>
          </div>
          <main className="p-4 font-mono text-sm">
            <h2 className="text-xl font-bold mb-4">Project File Tree</h2>
            <div className="bg-muted p-4 rounded-lg">
              {fileTree.map(item => (
                <div key={item.number} style={{ marginLeft: `${item.indent * 1}rem` }}>
                  <span className="text-destructive-foreground/50">{item.number}.</span>
                  <span className={item.type === 'folder' ? 'text-primary' : 'text-foreground'}> {item.name}</span>
                </div>
              ))}
            </div>
          </main>
        </ScrollArea>

        <footer className="flex-shrink-0 rounded-b-2xl border-x-2 border-b-2 border-t-2 border-destructive bg-muted p-2 text-destructive-foreground">
          <div className="flex items-center justify-between">
            <button
              onClick={() => router.back()}
              className="rounded-md p-2 hover:bg-destructive-foreground/10"
              aria-label="Go back"
            >
              <ArrowLeft strokeWidth={3} className="h-8 w-8" />
            </button>
            <div className="flex flex-col items-center">
                <Accessibility className="h-6 w-6" />
                <p className="text-center text-xs">
                    &copy; 2025 The-Law-Says.Com
                </p>
            </div>
            <button
              onClick={() => router.forward()}
              className="rounded-md p-2 hover:bg-destructive-foreground/10"
              aria-label="Go forward"
            >
              <ArrowRight strokeWidth={3} className="h-8 w-8" />
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}
